# Read the employee data
###
GET http://localhost:4004/odata/v4/catalog-services/EmployeeSrv

###
POST http://localhost:4004/odata/v4/catalog-services/createEmployee
Content-Type : application/json

{
  "Currency_code": "USD",
  "ID": "2a5776ec-e711-4c11-a92a-2da5b46c41a9",
  "accountNumber": null,
  "bankId": null,
  "bankName": null,
  "email": null,
  "gender": "M",
  "language": "E",
  "loginName": "RAMAM",
  "nameFirst": "Rama",
  "nameInitials": null,
  "nameLast": "Murthy",
  "nameMiddle": null,
  "phoneNumber": "(+1) 9898989898",
  "salaryAmount": "45000.00"
}

###
POST http://localhost:4004/odata/v4/catalog-services/createAddress
Content-Type: application/json

{
  "ADDRESS_TYPE": "HOME",
  "BUILDING": "A Block, Green Residency",
  "CITY": "Bangalore",
  "COUNTRY": "India",
  "LATITUDE": 12.9716,
  "LONGITUDE": 77.5946,
  "NODE_KEY": "11111111-1111-1111-1111-111111111111",
  "POSTAL_CODE": "560001",
  "STREET": "MG Road",
  "VAL_START": "2026-01-01",
  "VAL_END": "2030-12-31"
}

###
POST http://localhost:4004/odata/v4/catalog-services/updateEmployee
Content-Type:application/json

{
  "ID":"2a5776ec-e711-4c11-a92a-2da5b46c40a8",
  "salaryAmount": "50000.00",
  "Currency_code":"USD"
}


###
GET http://localhost:4004/odata/v4/catalog-services/ProductSrv


###
POST http://localhost:4004/odata/v4/catalog-services/createProduct
Content-Type: application/json

{
  "NODE_KEY": "dr455",
  "PRODUCT_ID": "P1001",
  "TYPE_CODE": "FG",
  "CATEGORY": "Electronics",
  "DESCRIPTION": "Laptop Computer",
  "TAX_TARIF_CODE": 18,
  "MEASURE_UNIT": "EA",
  "WEIGHT_MEASURE": 2.50,
  "WEIGHT_UNIT": "KG",
  "PRICE": 75000.00,
  "CURRENCY_CODE": "INR",
  "WIDTH": 35.00,
  "DEPTH": 24.00,
  "HEIGHT": 2.00,
  "DIM_UNIT": "CM"
}

###
POST http://localhost:4004/odata/v4/catalog-services/updateProduct
Content-Type:application/json

{
 "NODE_KEY": "dr455",
 "PRICE": "65000.00"
}

//deleteRequest
###
POST http://localhost:4004/odata/v4/catalog-services/deleteEmployee
Content-Type: application/json

{
  "ID":"2a5776ec-e711-4c11-a92a-2da5b46c41a9"
}

###
PUT http://localhost:4004/odata/v4/catalog-services/EmployeeSrv/02BD2137-0890-1EEA-A6C2-BB55C19787FB
Content-Type: application/json

{
    "salaryAmount": "105000.00",
    "currency_code": "USD"
}


###
PUT http://localhost:4004/odata/v4/catalog-services/PurchaseOrderSrv/74867AD200E41EDBA5D8B0CBD35A0052
Content-Type: application/json
 
{
    "GROSS_AMOUNT":"19000",
    "CURRENCY_code":"EUR"
}

###
GET http://localhost:4004/odata/v4/catalog-services/getHighestSalariedEmployees()

###
GET http://localhost:4004/odata/v4/catalog-services/getHighestPricedProduct()

###
POST http://localhost:4004/odata/v4/catalog-services/PurchaseOrderSrv/74867AD200E41EDBA5D8B0C98DC28052/discountPrice

###
GET http://localhost:4004/odata/v4/catalog-services/PurchaseOrderSrv/74867AD200E41EDBA5D8B0C98DC28052/largestOrder()

###
POST http://localhost:4004/odata/v4/catalog-services/ProductSrv/74867AD200E41EDBA5D8B0C98DC28052/increasePrice

###
GET http://localhost:4004/odata/v4/catalog-services/ProductSrv/44444444-4444-4444-4444-444444444444/top20Products

###
POST http://localhost:4004/odata/v4/catalog-services/EmployeeSrv/02BD2137-0890-1EEA-A6C2-BB55C19787FB/increaseSalary

###
GET http://localhost:4004/odata/v4/catalog-services/EmployeeSrv/02BD2137-0890-1EEA-A6C2-BB55C19787FB/top20HighestPaidEmployee()

### Read the employee data
GET http://localhost:4004/odata/v4/catalog-services/getUtilities()